version: "3.8"
services:
  chroma:
    image: chromadb/chroma:latest #ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - chroma-net

volumes:
  index_data:
    driver: local

networks:
  chroma-net:
    driver: bridge